console.log(window);
console.log(this);
console.log(window.document);
console.log(document.head);
console.log(document.body);
console.log(document.title);
document.title="DOM"
console.log(window.screen.availHeight);
console.log(window.screen.availWidth);